name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'sapmachine'
          java-version: '17'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: 'target/surefire-reports/*.xml'

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: exception-adder-jar
          path: target/*.jar