name: Build JAR

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'sapmachine'
          java-version: '17'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: (!cancelled())
        with:
          files: |
            test-results/**/*.xml
            test-results/**/*.trx
            test-results/**/*.json

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: exception-adder-jar
          path: target/*.jar